### ISSUE TITLE
Unexpected behavior from specFilter

### ISSUE THREAD

**Issue by Sayan751** [dfederm/karma-jasmine-html-reporter#11]
Lets say I have 2 top level test suites with following names: `Control Test Specs`, and `FancyControl Test Specs`. Now when I try to run the `Control Test Specs` test suite, both the test suites run.

This due to the fact [how the RegExp is built](https://github.com/dfederm/karma-jasmine-html-reporter/blob/master/src/lib/html.jasmine.reporter.js#L516-L520) for matching the specifications. For the above example, the RegExp pattern is formed as `/Control\ Test\ Specs/`, which matches both the test suite. Ideally only one test suite should be filtered, which can be done by using start and end markers in RegExp, like `/^TextBox\ test\ specs$/`.

**Comment by dfederm** [comment]
@Sayan751 Thanks. This whole package is really just [pulled from Jasmine itself](https://github.com/dfederm/karma-jasmine-html-reporter#develop), so I'd recommend making a fix [over there](https://github.com/jasmine/jasmine/blob/36360149177cd6d111d292d6425ffa8f34661ffc/lib/jasmine-core/jasmine-html.js#L541). Once that's fixed in Jasmine itself, I'd be happen to pull through the changes on my end.
