### ISSUE TITLE
Add option to disable has no expectations message

### ISSUE THREAD

**Issue by NetanelBasal** [dfederm/karma-jasmine-html-reporter#20]
Hey, Thanks for this great library.

When testing Angular applications, it's valid to have the following test:

```ts
it('can test HttpClient.get', () => {
  const testData: Data = {name: 'Test Data'};

  // Make an HTTP GET request
  httpClient.get<Data>(testUrl)
    .subscribe(data =>
      expect(data).toEqual(testData)
    );

  // The following `expectOne()` will match the request's URL.
  // If no requests or multiple requests matched that URL
  // `expectOne()` would throw.
  httpTestingController.expectOne('/data');

  httpTestingController.verify();
});
```

The problem is that we get the exception "Service ... has no expectations." for each test that uses this pattern. Can you add an option to disable this behavior, please?

**Comment by dfederm** [comment]
It seems like the problem in this case is that the `expect` you have is executed async, which means that it would execute after the test completes. I believe you'll want to use an async testing pattern instead.

**Comment by NetanelBasal** [comment]
No, it's not async. It's not a real HTTP request, Angular using mocks.

**Comment by dfederm** [comment]
Relevant stackoverflow: https://stackoverflow.com/a/45802383

Although it's using mocks, I doubt (or hope, for the sake of test correctness) that `subscribe` still defers the execution so that it gets pushed to the end of the event queue. If it executes synchronously, that would greatly deviate from "real" execution order and basically cause the test to be testing a case that could never happen. So I get that it's a mock and isn't really making a web request, but it must still be deferring the call and you can verify that using a debugger.

**Comment by NetanelBasal** [comment]
The tests pass. If I change the path, it doesn't pass. It's not async.

**Comment by dfederm** [comment]
Yes, the request is made synchronously, but the response would not come back synchronously.

If your subscription was being executed (and thus the `expect`), you would not see this warning. So it's definitely being executed after the test completes. Try making the test async and see what happens. Something like...

```ts
it('can test HttpClient.get', done => {
  const testData: Data = {name: 'Test Data'};

  // Make an HTTP GET request
  httpClient.get<Data>(testUrl)
    .subscribe(data =>
      expect(data).toEqual(testData);
      done(); // mark the test as actually done now.
    );

  // The following `expectOne()` will match the request's URL.
  // If no requests or multiple requests matched that URL
  // `expectOne()` would throw.
  httpTestingController.expectOne('/data');

  httpTestingController.verify();
});
```

**Comment by NetanelBasal** [comment]
I don't think so, but I will check and let you know. Thanks :)

**Comment by dfederm** [comment]
You can also use `fakeAsync` + `tick` or `async` (provided by angular) to help testing async stuff.

Or, according to the latest [docs](https://angular.io/guide/http#testing-http-requests) (which seem to have changed since I last looked at them), you need to call the following to cause the async call to flush:
```ts
  // The following `expectOne()` will match the request's URL.
  // If no requests or multiple requests matched that URL
  // `expectOne()` would throw.
  const req = httpTestingController.expectOne('/data');

  // Assert that the request is a GET. (dfederm: seems optional)
  expect(req.request.method).toEqual('GET');

  // Respond with mock data, causing Observable to resolve.
  // Subscribe callback asserts that correct data was returned.
  req.flush(testData);
```

**Comment by NetanelBasal** [comment]
It's not about the subscription, it's about the request.

```ts
it('can test HttpClient.get', () => {

  // Make an HTTP GET request
  httpClient.get(testUrl).subscribe();

  // The following `expectOne()` will match the request's URL.
  // If no requests or multiple requests matched that URL
  // `expectOne()` would throw.
  httpTestingController.expectOne('/data');

  httpTestingController.verify();
});
```

This code should work.

**Comment by dfederm** [comment]
Ah, yes in that case you actually don't have any `expects`. The confusion is that in your original code snippet you did have an `expect` and so I was trying to help you correct that since it seemed like that was the real issue.

So to address the actual ask of supporting a spec with no expectation, looks like that code is here: https://github.com/dfederm/karma-jasmine-html-reporter/blob/baa99b59a811b171b621bf19d2349d38551c51b6/src/lib/html.jasmine.reporter.js#L142,L144

However, this library is more or less just a copy of specific pieces of jasmine's html reporter for use with karma, so it's real origin is here:
https://github.com/jasmine/jasmine/blob/master/lib/jasmine-core/jasmine-html.js#L142,L144

So I think you should report this to the jasmine team and have it fixed there. Once fixed and released, I can sync their changes into this lib.

In the meantime, you can just add a dummy expectation to your test.

However, in general I do recommend that your test do more than just verify that a request was simply made and instead do some extra validation of any subscriptions and the response handling.

**Comment by NetanelBasal** [comment]
Sorry for the confusion. In the meantime, I monkey-patch `console.error`, and ignore the error pattern.

**Comment by NetanelBasal** [comment]
Thanks for the help.
