### ISSUE TITLE
Support for chai.expect

### ISSUE THREAD

**Issue by tstackhouse** [dfederm/karma-jasmine-html-reporter#37]
I'm using `jasmine-chai` to instrument a old(er) project that uses chai matchers in a lot of its tests and want ti use this reporter, but for all my tests the reporter complains about the specs having no expectations. I'd imagine that it's because something in the reporter isn't aware of chai's `expect`

**Comment by dfederm** [comment]
I can't find anything related to `jasmine-chai`, but if you mean [`chai-jasmine`](https://www.npmjs.com/package/chai-jasmine), I don't think this will work. According to the docs:

> chai-jasmine is an extension which provides Jasmine's style expect on top of mocha using chai assertion library.

So that implies it "looks like" Jasmine, but isn't actually.

Then later:

> Note: all features related to the Jasmine's specs runner (like Jasmine.Env()) ***or reporting*** won't have any effect anymore.

Based on this, I don't believe these packages will work together.

**Comment by tstackhouse** [comment]
That was my mistake, I was kind of code blind when I submitted this, I'm using `karma-jasmine` and `karma-chai`.  I believe we're using a combination of chai and jasmine matchers, though there are definitely more of the former.
